-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : jeu. 16 mars 2023 à 02:41
-- Version du serveur : 10.4.27-MariaDB
-- Version de PHP : 8.0.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `onlinebot`
--

-- --------------------------------------------------------

--
-- Structure de la table `chatbot`
--

CREATE TABLE `chatbot` (
  `id` int(11) NOT NULL,
  `response` varchar(7563) NOT NULL,
  `messages` varchar(7536) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `chatbot`
--

INSERT INTO `chatbot` (`id`, `response`, `messages`) VALUES
(0, 'Bonjour, comment puis-je vous aider aujourd\'hui ? Si vous cherchez des formations pour améliorer vos compétences professionnelles, je peux vous aider à trouver des options adaptées à vos besoins. Quel domaine vous intéresse le plus, par exemple le développement web, le marketing digital , design, la gestion de projet ,ou les langues étrangères ?\r\n(tapez \'formations\' pour voire les formations qu\'on vous propose)', 'bonjour'),
(1, 'Le développement web est le processus de création, de conception et de maintenance de sites web. Il implique la programmation de sites web dynamiques et interactifs, qui peuvent inclure des fonctionnalités telles que des formulaires de contact, des systèmes de gestion de contenu, des boutiques en ligne, des blogs, des forums, des médias sociaux, et bien plus encore.\r\n\r\nLe développement web implique souvent l\'utilisation de langages de programmation tels que HTML, CSS, JavaScript, PHP, Python et d\'autres technologies telles que des bases de données, des serveurs web et des frameworks pour simplifier et accélérer le processus de développement.\r\n\r\nLe développement web peut être réalisé par des individus travaillant de manière indépendante, des agences de développement web ou des équipes internes d\'entreprises qui cherchent à créer des sites web pour des besoins internes ou externes.\r\nvoici des excellentes ressource pour les futurs développeurs web  .\r\n<br>\r\n<a href=\"https://developer.mozilla.org/fr/docs/Learn\">mozilla</a><br>\r\n<a href=\"https://openclassrooms.com/fr/paths/717-developpeur-web \">\r\nopenclassrooms</a><br>\r\n                             \r\n\r\n\r\non vous propose aussi des formations sur youtube dans les langages suivantes (tapez le nom de la formation souhaitée)\r\n\r\n-HTML/CSS<br>\r\n-JAVASCRIPT/Type script<br>\r\n-PHP<br>\r\n-PYTHON<br>\r\n-FRAMORKS<br>\r\n-base de données\r\n\r\n', 'developpement web '),
(3, 'youtub                                        >\r\n<a href=\"https://youtu.be/u5W2NWItytc\">cliquez ici</a>  <br>                   .\r\nQCM                                           >       \r\n<a href=\"https://waytolearnx.com/\r\ncategory/qcm-html-css\">cliquez ici</a>\r\n                                                       ', 'HTML/CSS'),
(4, 'https://youtu.be/yUndnE-2osg', 'TYPESCRIPT'),
(5, 'https://youtu.be/PWuTLTFMtYw', 'JAVASCRIPT'),
(6, 'https://youtu.be/h3VCQjyaLws', 'PYTHON'),
(7, 'https://youtu.be/sVbEyFZKgqk', 'PHP'),
(8, 'SQL-ORACLE-NoSQL', 'base de données'),
(9, 'https://youtu.be/pKuOAqKpGdw', 'SQL'),
(10, 'https://youtu.be/qEhNHOEa5sE', 'NoSQL'),
(11, 'vous pouvez choisir                            :\r\nReact                                             \'\r\nANGULAR                                                     \'\r\nLARAVEL                                                              \'\r\nSPRINGBOOT', 'FRAMEWORKS'),
(12, 'https://youtu.be/bMknfKXIFA8', 'React'),
(13, 'https://youtu.be/mg3-Owd5dhE', 'Angular'),
(14, 'https://youtu.be/32nxP0RuMlQ', 'LARAVEL'),
(15, 'Le graphisme désigne l\'ensemble des techniques, des compétences et des outils utilisés pour concevoir et réaliser des créations graphiques, qu\'il s\'agisse de supports imprimés, numériques ou visuels.\r\n\r\nLe graphisme peut inclure la création de logos, de brochures, de flyers, de cartes de visite, de panneaux publicitaires, de pages web, d\'interfaces utilisateur, de supports de communication visuelle, de packaging, de livres, de magazines, d\'affiches, de publicités, de vidéos, de présentations et bien plus encore.\r\n\r\nLes graphistes utilisent souvent des logiciels spécialisés tels que Photoshop, Illustrator, InDesign et d\'autres outils pour créer des visuels attrayants et efficaces qui répondent aux besoins spécifiques de leurs clients ou de leur public cible.\r\n\r\nLe graphisme est un domaine important dans la communication visuelle, la publicité, le marketing, le design, la culture, l\'art et de nombreux autres domaines où la création visuelle est essentielle.\r\nsi vous êtes intéressé au domaine tapez \"GDR\"  \r\n\r\n\r\n', 'graphique designe'),
(16, 'formation sur youtube                           >\r\nhttps://youtu.be/mOixLjMOJb4\r\nformation payée                                 >\r\nhttps://www.udemy.com/course/photoshop-cc/', 'photoshop'),
(17, 'formation payée                                 >\r\nhttps://www.elephorm.com/abonnement/forfaits\r\nformation sur youtub                            >\r\nhttps://youtu.be/ouDICXmug-M', 'illustrator'),
(18, 'https://youtu.be/Fm0uikrZaYY', 'inDesign'),
(20, 'L\'e-commerce (ou commerce électronique) est l\'ensemble des activités commerciales qui se déroulent sur Internet, par le biais d\'un site web, d\'une application mobile ou d\'une plateforme de commerce électronique.<br>\r\n\r\nL\'e-commerce permet aux entreprises de vendre leurs produits ou services en ligne, de manière à ce que les clients puissent commander et payer pour leurs achats via Internet. Les transactions sont généralement effectuées en temps réel, ce qui permet aux clients de recevoir rapidement leur commande et aux entreprises de gérer efficacement leur stock et leurs livraisons.<br>\r\n\r\nL\'e-commerce a connu une croissance rapide ces dernières années, en grande partie grâce à la commodité, la flexibilité et l\'accessibilité qu\'il offre aux clients. Les entreprises peuvent également bénéficier d\'une portée élargie, d\'une réduction des coûts liés aux ventes en magasin physique et d\'une augmentation des ventes grâce à des campagnes de marketing ciblées et des programmes de fidélisation.<br>\r\nvoila une formation sur youtub:\r\n <a href=\"https://youtu.be/y_b_MvZu6Jo\">cliquez ici</a>\r\n<><br>\r\nLes 10 meilleures plateformes e-commerce:<br>\r\n<a href=\"\r\nhttps://digitiz.fr/blog/plateformes-ecommerce\">cliquez ici</a>\r\n', 'e-comerce'),
(21, 'Le marketing digital est une pratique de promotion de produits, de services ou de marques en utilisant des canaux de communication numériques tels que les moteurs de recherche, les réseaux sociaux, les e-mails, les sites web et les applications mobiles. Il englobe l\'utilisation de diverses techniques et outils de marketing numérique pour atteindre et engager un public cible, renforcer la notoriété de la marque, générer des prospects et des ventes, et finalement réaliser la croissance de l\'entreprise.\r\n\r\nLe marketing digital inclut un large éventail de tactiques, notamment l\'optimisation des moteurs de recherche (SEO), la publicité au paiement par clic (PPC), le marketing de contenu, le marketing des réseaux sociaux, le marketing par e-mail et le marketing mobile. Ces stratégies peuvent être adaptées aux besoins et objectifs spécifiques d\'une entreprise, et peuvent être mesurées et optimisées pour une efficacité maximale.\r\n\r\nLa montée des technologies numériques et d\'Internet a transformé la façon dont les entreprises se promeuvent et interagissent avec les clients. Le marketing digital permet aux entreprises d\'atteindre un public plus large, de construire des relations avec les clients et de suivre l\'efficacité de leurs campagnes en temps réel. Un marketing digital efficace nécessite une compréhension approfondie de l\'audience cible, une volonté de s\'adapter aux tendances et aux technologies en constante évolution, et une approche axée sur les données pour la prise de décision.\r\n\r\n\r\n\r\n\r\n\r\n                             > vous pouvez consulter ce lien               :\r\nhttps://youtu.be/Q3v5tVxkkck\r\nsi voulais vous consultez les formations  : seo-marketing par e-mail-publicité en ligne-design-gestion de projet .(il suffit de tapper le nom de la formation souhaitée)', 'digital marketing '),
(22, 'La communication peut être améliorée par le développement de compétences telles que l\'écoute active, l\'empathie, la clarté, la concision, la confiance en soi, la gestion du stress et des émotions, la capacité à s\'adapter à différents publics, etc. Les technologies de l\'information et de la communication ont également un impact important sur la manière dont nous communiquons et interagissons les uns avec les autres\r\n\r\nce lien va vous aider :\r\nhttps://youtu.be/xqt2kE3Pft8', 'communication'),
(23, 'La rédaction est un élément clé du marketing digital. Vous devrez être capable de créer des messages clairs, concis et accrocheurs pour vos différents canaux de communication.', 'Compétences en rédaction'),
(25, 'Le référencement naturel est important pour que votre site web soit facilement trouvé par les clients sur les moteurs de recherche. Vous devrez être capable d\'optimiser le contenu de votre site web pour améliorer son classement sur les moteurs de recherche. \r\nvous pouvez consultez ce lien pour plus d\'info:\r\nhttps://youtu.be/w6nUN7ME0qw\r\n', 'seo'),
(26, ' Le marketing par e-mail est un élément important du marketing digital. Vous devrez être capable de créer des messages efficaces et de gérer des listes de diffusion pour atteindre votre public.\r\nhttps://youtu.be/Zz_rsCkhLVE', 'Compétences en marketing par e-mail'),
(27, 'Les compétences en publicité en ligne sont importantes pour créer des campagnes publicitaires efficaces sur différents canaux de publicité en ligne, tels que les réseaux sociaux et les moteurs de recherche.\r\nlien:\r\nhttps://youtu.be/lQ2oyvlOaZc\r\n', 'Compétences en publicité en ligne'),
(28, 'Les compétences en gestion de projet sont importantes pour gérer efficacement les différents projets  assurer leur achèvement dans les délais impartis                    .\r\ndans ce lien vous allez trouver une formation en gestion de projet:\r\nhttps://youtu.be/T4RVB-fZFnQ\r\n\r\n', 'gestion de projet'),
(30, 'La résolution de problèmes implique plusieurs étapes clés, telles que :\r\n\r\nIdentifier le problème : Comprendre clairement le problème et ses causes.\r\n\r\nCollecter des données : Obtenir des informations pertinentes sur le problème.\r\n\r\nAnalyser les données : Examiner les informations pour comprendre la nature du problème.\r\n\r\nGénérer des idées : Trouver différentes solutions possibles au problème.\r\n\r\nÉvaluer les options : Évaluer chaque solution en fonction de ses avantages et inconvénients.\r\n\r\nChoisir une solution : Sélectionner la meilleure solution en fonction de l\'évaluation.\r\n\r\nMettre en œuvre la solution : Appliquer la solution choisie.\r\n\r\nSuivre les résultats : Évaluer l\'efficacité de la solution et apporter des modifications si nécessaire.\r\n\r\nPour améliorer votre compétence en résolution de problèmes, vous pouvez développer des compétences telles que la pensée critique, la créativité, la flexibilité, la persévérance, la collaboration et la communication. Il est également important de travailler sur votre capacité à gérer le stress et à prendre des décisions éclairées sous pression.\r\n\r\nEnfin, il est important de se rappeler que la résolution de problèmes est une compétence qui peut être améliorée avec la pratique. En travaillant sur différents types de problèmes et en apprenant de vos expériences, vous pouvez renforcer votre capacité à résoudre efficacement les problèmes.\r\nLa résolution de problèmes implique plusieurs étapes clés, telles que :\r\n\r\nIdentifier le problème : Comprendre clairement le problème et ses causes.\r\n\r\nCollecter des données : Obtenir des informations pertinentes sur le problème.\r\n\r\nAnalyser les données : Examiner les informations pour comprendre la nature du problème.\r\n\r\nGénérer des idées : Trouver différentes solutions possibles au problème.\r\n\r\nÉvaluer les options : Évaluer chaque solution en fonction de ses avantages et inconvénients.\r\n\r\nChoisir une solution : Sélectionner la meilleure solution en fonction de l\'évaluation.\r\n\r\nMettre en œuvre la solution : Appliquer la solution choisie.\r\n\r\nSuivre les résultats : Évaluer l\'efficacité de la solution et apporter des modifications si nécessaire.\r\n\r\nvous pouvez consultez ce lien pour plus d\'information \r\nhttps://youtu.be/B57nRnKrz-E', 'résolution de problème'),
(31, 'La finance est un domaine très vaste qui englobe une grande variété de sujets. Voici quelques informations générales sur la finance :\r\n\r\nLes trois principales décisions financières : Les décisions financières peuvent être classées en trois catégories principales : les décisions d\'investissement, les décisions de financement et les décisions de distribution des dividendes.\r\n\r\nLes marchés financiers : Les marchés financiers sont des lieux où les investisseurs peuvent acheter et vendre des titres tels que des actions, des obligations et des devises. Les marchés financiers sont essentiels pour le fonctionnement de l\'économie mondiale.\r\n\r\nLes produits financiers : Les produits financiers sont des instruments financiers qui peuvent être achetés ou vendus sur les marchés financiers. Les produits financiers comprennent des actions, des obligations, des options, des contrats à terme et des produits dérivés.\r\n\r\nLes taux d\'intérêt : Les taux d\'intérêt sont un élément clé de la finance. Ils sont utilisés pour déterminer le coût du crédit et le rendement des investissements.\r\n\r\nLa gestion des risques : La gestion des risques est un domaine important de la finance. Les entreprises et les investisseurs utilisent des techniques de gestion des risques pour minimiser les pertes potentielles associées aux fluctuations des marchés financiers.\r\n\r\nLes systèmes financiers : Les systèmes financiers sont des structures qui permettent la circulation de l\'argent et des capitaux. Les systèmes financiers peuvent être nationaux ou internationaux.\r\n\r\nLa réglementation financière : La réglementation financière est l\'ensemble des règles et des lois qui régissent le secteur financier. Les réglementations financières sont mises en place pour protéger les investisseurs et maintenir l\'intégrité des marchés financiers.\r\n\r\nLes métiers de la finance : Les métiers de la finance incluent des postes tels que analyste financier, gestionnaire de portefeuille, banquier d\'investissement et comptable. Ces professions exigent souvent des compétences analytiques avancées et une bonne compréhension des marchés financiers.\r\nlien:\r\nhttps://diplomeo.com/formation-finance\r\n', 'la finance'),
(32, 'Le leadership est la capacité de diriger, d\'influencer et d\'inspirer un groupe de personnes pour atteindre un objectif commun. Un bon leader est capable de motiver son équipe à travailler ensemble pour atteindre un but, tout en offrant un soutien et une orientation. Les compétences de leadership sont essentielles pour les entreprises, les organisations, les gouvernements et d\'autres groupes.\r\nhttps://youtu.be/UbCgj-H7Uzs', 'Ledership'),
(33, 'Anglais                                          >\r\nhttps://youtu.be/SoR6YO3AE74\r\nFrançais                                         >\r\nhttps://youtu.be/4fY01bnJ5nc\r\nAllemande                                        >\r\nhttps://youtu.be/KXpMQG8rDLc', 'Langues'),
(34, '-développement web <br>              \r\n-design<br>                     \r\n-digital marketing <br>\r\n-e-commerce <br>\r\n-Freelance<br> \r\n- Affiliate Marketing<br> \r\n- Dropshipping<br>\r\n-dropservicing <br>\r\n- POD (pinting on demand) <br>\r\n- COD (Cash on Delevery) <br>               \r\ngestion de projet <br>\r\n-Leadership<br>\r\n-finance <br>\r\n\r\n-Langues<br>\r\n-communication<br>\r\n-résolution de problème', 'formations'),
(35, 'Il existe de nombreuses ressources en ligne pour apprendre à maîtriser le graphisme et le design graphique. Voici quelques suggestions pour commencer                              >\r\n\r\nCoursera : Coursera propose de nombreux cours en ligne sur le design graphique, dispensés par des universités renommées telles que California Institute of the Arts, University of Colorado Boulder et University of Michigan.            <>\r\n\r\nUdemy : Udemy est une plateforme de formation en ligne qui propose de nombreux cours sur le design graphique, allant des bases aux techniques avancées.                         <>\r\n\r\nAdobe Creative Cloud : Adobe Creative Cloud est une suite de logiciels de création graphique, tels que Photoshop, Illustrator et InDesign. Adobe propose également des tutoriels en ligne pour apprendre à utiliser ces logiciels.         <>\r\n\r\nCanva : Canva est un outil de conception graphique en ligne qui permet de créer des designs professionnels sans avoir besoin de compétences en design. Canva propose également des tutoriels en ligne pour aider les utilisateurs à maîtriser la plateforme.          <>\r\n\r\nYouTube : YouTube regorge de vidéos de tutoriels sur le design graphique. Les créateurs de contenu tels que The Futur, Dansky, et Will Paterson offrent des conseils et astuces pour apprendre les bases et développer des compétences plus avancées.        <>\r\n\r\nLivres sur le design graphique : Il existe de nombreux livres sur le design graphique, couvrant des sujets tels que la typographie, la composition et la couleur. Certaines recommandations populaires incluent \"Thinking with Type\" de Ellen Lupton, \"The Elements of Typographic Style\" de Robert Bringhurst, et \"Designing Brand Identity\" de Alina Wheeler.\r\n                                     <>\r\nEn utilisant ces ressources, vous pouvez apprendre à maîtriser le graphisme et le design graphique à votre propre rythme et développer les compétences nécessaires pour créer des designs professionnels et percutants.<>\r\nOn vous propose aussi des formation sur Youtube en Photoshop-InDesign-Illustrateur (tapez le nom de la formation souhaité )', 'GDR'),
(36, 'Définition : freelance une personne qui exerce une activité professionnelle avec la qualité de travailleur indépendant. Ce collaborateur n\'a pas de contrat à long terme comme les salariés en CDD ou CDI, mais réalise son activité professionnelle sous la forme de missions, qu\'il facture à ses clients\r\nLien vidéo youtube : https://www.youtube.com/watch?v=iorpzjUsPfM', 'freelance'),
(37, 'Définition : Le drop shipping est une forme de e-commerce par laquelle le site vendeur ne possède pas de stocks et fait livrer le client final directement par son fournisseur sans, le plus souvent, que le client ne le sache. Le principe du drop shipping peut être utilisé pour une partie de l\'assortiment du site marchand ou pour la totalité de l\'offre.\r\n', 'Drop shipping'),
(38, 'Le marketing d\'affiliation est un type de marketing basé sur la performance dans lequel un annonceur récompense un ou plusieurs affiliés pour chaque client ou visiteur apporté par les efforts de marketing de l\'affilié. En d\'autres termes, les affiliés promeuvent les produits ou services de l\'annonceur via divers canaux tels que des sites web, les médias sociaux, le marketing par e-mail, etc.\r\n\r\nLorsqu\'un client clique sur le lien d\'un affilié et effectue un achat ou réalise une action spécifique telle que remplir un formulaire, l\'affilié reçoit une commission ou une autre forme de compensation de l\'annonceur. Le montant de la commission varie en fonction de l\'annonceur et des termes spécifiques de l\'accord d\'affiliation.\r\n\r\nLe marketing d\'affiliation est populaire car il permet aux annonceurs d\'élargir leur portée et d\'augmenter leurs ventes sans supporter des coûts publicitaires élevés initialement. Il permet également aux affiliés de générer des revenus passifs en promouvant des produits en lesquels ils croient sans avoir à investir dans des stocks ou le développement de produits\r\nvoici une formation:\r\nhttps://youtu.be/9G_AbWzJ5uw\r\nLes 13 meilleures plateformes d’affiliation marketing en 2023\r\nhttps://www.codeur.com/blog/plateformes-affiliation-marketing/\r\n\r\n\r\n', 'Affiliate marketing'),
(39, 'Le dropservicing est un modèle d\'entreprise similaire au dropshipping, mais plutôt que de vendre des produits physiques, il consiste à vendre des services proposés par des prestataires tiers à des clients finaux.\r\n\r\nConcrètement, un dropservicer va proposer des services tels que la création de site web, la rédaction de contenu, la gestion des réseaux sociaux, la traduction de documents, etc. à des clients finaux. Cependant, au lieu de fournir ces services lui-même, il va sous-traiter le travail à des prestataires tiers, généralement à l\'étranger, qui réalisent le travail pour lui à un coût inférieur.\r\n\r\nLe dropservicing est attractif pour les entrepreneurs qui souhaitent se lancer sans avoir à investir dans des compétences spécifiques ou du personnel à plein temps. Cependant, il nécessite une solide gestion de projet et de bonnes compétences en communication pour s\'assurer que le travail est réalisé de manière satisfaisante pour le client final.\r\nconsultez ce lien pour plus d\'info\r\nhttps://youtu.be/0SmpOMrv5qc', 'dropservicing'),
(40, 'Les produits numériques, également connus sous le nom de produits digitaux ou produits virtuels, sont des produits qui sont créés et distribués sous forme de fichiers numériques plutôt que sous forme physique. Les produits numériques peuvent inclure une grande variété de types de contenus, tels que des livres électroniques, des vidéos en ligne, des logiciels, des cours en ligne, des fichiers audio, des applications mobiles et des jeux vidéo.\r\n\r\nL\'avantage des produits numériques est qu\'ils peuvent être facilement et rapidement distribués à un large public via Internet, sans coûts de production ou de distribution importants. De plus, les produits numériques peuvent être facilement mis à jour ou améliorés, et ils peuvent être vendus à un prix relativement élevé car leur coût marginal est souvent très faible.\r\n\r\nLes produits numériques sont populaires auprès des entrepreneurs et des créateurs qui cherchent à créer une entreprise en ligne ou à générer un revenu supplémentaire grâce à leurs compétences et connaissances spécialisées\r\nlien video youtube:\r\nhttps://youtu.be/f4csYziqoIU\r\nLes 13 meilleures plateformes d’affiliation marketing en 2023\r\nhttps://www.wizishop.fr/blog/plateforme-vendre-produits-numeriques', 'digital product'),
(42, 'Avec l\'impression à la demande, un livre ou un autre objet imprimé n\'est imprimé que lorsqu\'il est commandé, ce qui élimine le besoin de stockage coûteux et réduit les déchets. Cette technologie a révolutionné l\'industrie de l\'édition, permettant aux auteurs et éditeurs indépendants de produire et de distribuer leur travail sans avoir besoin d\'un investissement initial important.\r\nconsultez ce lien:\r\nhttps://www.printful.com/fr/print-on-demand', 'POD'),
(43, 'Cash on Delivery (COD) est un mode de paiement couramment utilisé dans le commerce électronique ou les transactions commerciales. Dans une transaction COD, l\'acheteur effectue le paiement de la commande en espèces au moment de la livraison de la marchandise. En d\'autres termes, le paiement n\'est effectué qu\'après que l\'acheteur ait reçu la marchandise commandée. Ce mode de paiement est souvent utilisé lorsque l\'acheteur et le vendeur ne se connaissent pas ou ne sont pas en mesure de se faire confiance mutuellement pour effectuer un paiement à l\'avance.\r\npour plus d\'info :\r\nhttps://www.investopedia.com/terms/c/cashondelivery.asp', 'cod');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `chatbot`
--
ALTER TABLE `chatbot`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
